kind: ServiceAccount
apiVersion: v1
metadata:
  name: reaper-user
  namespace: default

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: reaper
rules:
- apiGroups: ["", "apps", "batch"]
  resources: ["pods", "deployments", "services", "jobs"]
  verbs: ["get", "list", "delete"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: reaper-role-binding
subjects:
- kind: ServiceAccount
  name: reaper-user
  namespace: default
roleRef:
  kind: Role
  name: reaper
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: reaper
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: reaper-user
          containers:
            - name: reaper
              image: m0wfo/reaper:1.0.0-SNAPSHOT
              env:
                - name: LABEL_SELECTOR
                  value:  "branch, branch notin (develop, master)"
          restartPolicy: Never
